# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  Azure Pipelines

stages:
- stage: 'Build'
  displayName: 'Deploy'
  jobs:
  - deployment: Build
    pool:
      vmImage: windows-latest
  - job: 'Build'
    displayName: 'Deploy job'
    pool:
      Azure Pipelines
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'Test'
        organization: 'sahanaumesh'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sahanasu93_example1'
        cliProjectName: 'example1'
        cliSources: '.'
    - task: SonarCloudAnalyze@1

    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

    - task: CopyFiles@2
      inputs:
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(Pipeline.Workspace)'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

- stage: 'StageA'
  displayName: 'BuildA'
  jobs: 
  - deployment: Deploy
    pool:
      vmImage: windows-latest
    environment: dev
  - job: 'Build'
    displayName: 'Build job'
    pool:
      Azure Pipelines
    steps:
    - script: echo Hello, world A!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

  - job: 'BuildB'
    displayName: 'Build job'
    steps:
    - script: echo Hello, world B!
      displayName: 'Run a one-line script'

- stage: 'StageB'
  displayName: 'BuildB'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    steps:
    - script: echo Hello, world A!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

  - job: 'BuildB'
    displayName: 'Build job'
    steps:
    - script: echo Hello, world B!
      displayName: 'Run a one-line script'

