# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  Azure Pipelines

stages:
- stage: 'StageA'
  displayName: 'Build code'
  jobs: 
  - deployment: Deploy
    pool:
      vmImage: windows-latest
    environment: dev
  - job: 'Build'
    displayName: 'Build job'
    pool:
      Azure Pipelines
    steps:
    - script: echo Hello, world A!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

  - job: 'BuildB'
    displayName: 'Build job'
    steps:
    - script: echo Hello, world B!
      displayName: 'Run a one-line script'

- stage: 'StageB'
  displayName: 'Build code'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    steps:
    - script: echo Hello, world A!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

  - job: 'BuildB'
    displayName: 'Build job'
    steps:
    - script: echo Hello, world B!
      displayName: 'Run a one-line script'

